name: CI
run-name: CI Build
on: 
  push:
    branch:
    - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zizizach/flappybird:${{github.ref_name}}
      - name: get-credential-secret
        run: echo "${{ secrets.GCPCREDENTIAL }}" >> "${{github.ACTION_PATH}}/terraform/zachgpt-f8a69433fb95.json"
      - name: terraform
        run: |
          cd terraform
          terraform init
          ls -lrt
        